Repository clappr/clappr-ios, pull requests merged in 2020-10, with the labels that each got.

#404 Disable external playback
  Sources/Clappr/Classes/Base/Options.swift
  Sources/Clappr/Classes/Plugin/Playback/AVFoundationPlayback.swift
Labels: in progress

#406 Create MediaControl layer
  Clappr.xcodeproj/project.pbxproj
  Sources/Clappr/Classes/Base/Core.swift
  Sources/Clappr/Classes/Base/Layers/LayerComposer.swift
  Sources/Clappr/Classes/Base/Layers/MediaControlLayer.swift
  Tests/Clappr_Tests/Classes/Base/Layers/LayerComposerTests.swift
  Tests/Clappr_Tests/Classes/Base/Layers/MediaControlLayerTests.swift
  Tests/Clappr_Tests/Classes/Plugin/Core/CoreTests.swift
  Tests/Clappr_Tests/Classes/Plugin/Core/MediaControl/QuickSeekMediaControlPluginTests.swift
Labels: do not merge, in progress

#411 Close bottom drawer plugin only if it's open on orientation change
  Sources/Clappr_iOS/Classes/Plugin/Core/Drawer/BottomDrawerPlugin.swift
Labels: done
